### ISSUE TITLE
Возможно, опечатка

### ISSUE THREAD

**Issue by vient** [windavid/return_to_fixup#1]
В теории есть строка 

> Для return_to_libc так же требуется memory-leak и контроль eip, но return_to_libc позволяет писать более надежные эксплоиты, не зависящие от версии libc.

Насколько я понимаю, return_to_libc как раз зависит от версии libc, и более надёжным тут является return_to_fixup.

**Comment by windavid** [comment]
Все верно, нужно исправить. Спасибо!

**Comment by vient** [comment]
Аналогично, итоги https://github.com/windavid/return_to_fixup/blob/master/2_practice.md#Итоги выглядят странно.

**Comment by windavid** [comment]
Да, тут уже просто проблемы с русским языком...
